using MessagePack;
using MessagePack.Resolvers;
using UnityEngine;

public class Startup
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    static void RegisterResolvers()
    {
        // NOTE: Currently, CompositeResolver doesn't work on Unity IL2CPP build. Use StaticCompositeResolver instead of it.
        StaticCompositeResolver.Instance.Register(
            // This resolver is generated by MagicOnion's code generator.
            MagicOnion.Resolvers.MagicOnionResolver.Instance,
            // This resolver is generated by MessagePack's code generator.
            MessagePack.Resolvers.GeneratedResolver.Instance,
            StandardResolver.Instance
        );

        MessagePackSerializer.DefaultOptions = MessagePackSerializer.DefaultOptions
            .WithResolver(StaticCompositeResolver.Instance);
    }
}